### PR TITLE
Update to .Net 6 and new minimal hosting model.

### PR DESCRIPTION
**Pull request by premgan**
## Purpose
Update to .Net 6 and new minimal hosting model.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x ] Other... Please describe: Updating to latest .Net
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by mahoekst** [comment]
I just tried to run this PR on my machine and it cannot connect to http://localhost:5000 anymore.

**Comment by premgan** [comment]
> I just tried to run this PR on my machine and it cannot connect to http://localhost:5000 anymore.

Is the IIS Express profile running for you ?

**Comment by mahoekst** [comment]
I am not using IIS (it needs to run on http to make NGROK work and other reverse proxies), I just use the regular .net project to run the samples.

**Comment by premgan** [comment]
> I am not using IIS (it needs to run on http to make NGROK work and other reverse proxies), I just use the regular .net project to run the samples.

I understand yes but localhost:5000 is connecting just fine on my machine, so I was wondering if port is a problem since IIS profile uses different port.

**Comment by mahoekst** [comment]
Sorry, its a 404 I get :

This localhost page can’t be foundNo webpage was found for the web address: http://localhost:5000/
HTTP ERROR 404

**Comment by mahoekst** [comment]
Ah, it works in VS 2022, does not work in VS 2019

**Comment by mahoekst** [comment]
The dependency on VS2022 is too big right now. The changes to move the solution to .NET 6 are minimal and little benefit to clarify the current samples for the VC APIs

**Pull request closed without merging**
